### ISSUE TITLE
Change communication with Siteimprove API to go via service instead of REST 

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-siteimprove#17]
Often when I re-deploy the siteimprove app, it will show a yellow error message, saying /admin/rest not found or similar.

Using /admin/rest is not a future-proof way of building backends for admin. We should have implemented the endpoint as a "Service". Services are normally done with Javascript, but we can use Java inside via Java beans. See the [styles service in app-contentstudio](https://github.com/enonic/app-contentstudio/blob/epic-6622/src/main/resources/services/styles/styles.js) for an example.

**Comment by alansemenov** [comment]
REST service was done in Java because we had it implemented in Java for the VWO app which has very similar functional to Siteimprove, so we basically copied the behaviour to save some time.

We should decide on the general best practice when implementing communication with external API so that we know what to do when we implement this behaviour for a future app.

Here are the alternatives:
1. Keep everything as it is (REST API in Java inside the Siteimprove app which communicates to Siteimprove API).
2. Move communication with Siteimprove API to client-side entirely. App validation (check of app account/token) will still be on the server-side of course, but all requests to Siteimprove API will be sent from client-side.
3. Keep communication with Siteimprove API in Java, but drop the Java REST service. Implement server-side Javascript service which will communicate with Java code via bean. Client-side will then call this service instead of current Java REST API.
4. Implement server-side Javascript service that will use *lib-http-client* to communicate with Siteimprove API. Validation can also be moved to this service - config properties can be accessed via ``app.config.propertyName``.

**Comment by edloidas** [comment]
As you probably saw, I've stuck with the third option. But let us talk about all of them:
1. I still think it's a good solution, but, as we saw, not the most reliable one. And it won't solve the original issue.
2. We can't do this kinda things without some serious hacks. It's against the Cross-Origin browser policy: you just can't send requests to another URL from the browser. Security reasons.
3. It's not requiring a lot of code to make things work when updating the first solution. It's safer and fixes the problem. But, it requires the most code of all other solutions. 
4. The best solution, but not for this app. The reason is that we'll need to write a lot of new code and it'll just take the hell of a time. But, if I'll have to write the app from scratch now, I'll do this way. But, ideally, we should wait for the newer version of the ES (hello, XP 7.*). Writing code in ES6 will be more secure, faster and cleaner. And we still don't have the debug option. But, in the future, we should prefer this solution, in my opinion.
